openapi: 3.0.0
info:
  title: Podman Desktop AI Lab API
  description: API for interacting with the Podman Desktop AI Lab service.
  version: 0.0.1
servers:
  - url: http://{host}:{port}
    description: Podman Desktop AI Lab API server
    variables:
      host:
        default: 127.0.0.1
      port:
        default: '10434'

tags:
  - name: server
    description: Server information

paths:
  /api/version:
    get:
      operationId: getServerVersion
      tags:
        - server
      description: Return the Podman Desktop AI Lab API server version
      summary: Return the Podman Desktop AI Lab API server version
      responses:
        '200':
          description: The Podman Desktop AI Lab API server version was successfully fetched
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  version:
                    type: string
                required:
                - version
  /api/tags:
    get:
      operationId: getModels
      tags:
        - models
      description: List models that are available locally
      summary: List models that are available locally
      responses:
        '200':
          description: The models were successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse'

components:
  schemas:
    ListResponse:
      type: object
      description: Response from a list request
      properties:
        models:
          type: array
          items:
            $ref: '#/components/schemas/ListModelResponse'

    ListModelResponse:
      type: object
      description: Response from a list request
      properties:
        name:
          type: string
        model:
          type: string
        modified_at:
          type: string
          format: date-time
        size:
          type: integer
        digest:
          type: string
        details:
          $ref: '#/components/schemas/ModelDetails'

    ModelDetails:
      type: object
      description: Details about a model
      properties:
        parent_model:
          type: string
        format:
          type: string
        family:
          type: string
        families:
          type: array
          items:
            type: string
        parameter_size:
          type: string
        quantization_level:
          type: string
