# This is a basic workflow that is manually triggered

name: Compute model sizes

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  compute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v5
    # Runs a single command using the runners shell
    - name: Compute model size
      run: ./tools/compute-model-sizes.sh
