#
# Copyright (C) 2025 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: ramalama

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:
    inputs:
      tag:
        default: 'latest'
        description: 'Ramalama images tag to use'
        type: string
        required: true

jobs:
  e2e-check:
    name: e2e tests
    runs-on: ubuntu-24.04
    env:
      SKIP_INSTALLATION: true
    steps:
      - uses: actions/checkout@v4
        with:
          path: podman-desktop-extension-ai-lab
      # Set up pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          package_json_file: ./podman-desktop-extension-ai-lab/package.json
      # Install Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      # Checkout podman desktop
      - uses: actions/checkout@v4
        with:
          repository: podman-desktop/podman-desktop
          ref: main
          path: podman-desktop

      - name: Update podman
        run: |
          # ubuntu version from kubic repository to install podman we need (v5)
          ubuntu_version='23.04'
          sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
          curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo apt-key add -
          # install necessary dependencies for criu package which is not part of 23.04
          sudo apt-get install -qq libprotobuf32t64 python3-protobuf libnet1
          # install criu manually from static location
          curl -sLO http://cz.archive.ubuntu.com/ubuntu/pool/universe/c/criu/criu_3.16.1-2_amd64.deb && sudo dpkg -i criu_3.16.1-2_amd64.deb
          sudo apt-get update -qq
          sudo apt-get -qq -y install podman || { echo "Start fallback steps for podman nightly installation from a static mirror" && \
            sudo sh -c "echo 'deb http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list" && \
            curl -L "http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo apt-key add - && \
            sudo apt-get update && \
            sudo apt-get -y install podman; }
          podman version

      - name: Revert unprivileged user namespace restrictions in Ubuntu 24.04
        run: |
          # allow unprivileged user namespace
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Set cgroup_manager to 'cgroupfs' instead of systemd
        run: |
          mkdir -p ~/.config/containers
          cat <<EOT >> ~/.config/containers/containers.conf
          [engine]
          cgroup_manager="cgroupfs"
          EOT
          podman info

      - name: Install pnpm deps and build Podman Desktop
        working-directory: ./podman-desktop
        run: |
          pnpm install --frozen-lockfile
          pnpm test:e2e:build

      - name: Ensure getting current HEAD version of the test framework
        working-directory: ./podman-desktop-extension-ai-lab/tests/playwright
        run: |
          # workaround for https://github.com/podman-desktop/podman-desktop-extension-bootc/issues/712
          version=$(npm view @podman-desktop/tests-playwright@next version)
          echo "Version of @podman-desktop/tests-playwright to be used: $version"
          jq --arg version "$version" '.devDependencies."@podman-desktop/tests-playwright" = $version' package.json > package.json_tmp && mv package.json_tmp package.json

      - name: Execute pnpm in AI Lab Extension
        working-directory: ./podman-desktop-extension-ai-lab
        run: pnpm install --no-frozen-lockfile

      - name: Update ramalama image references in AI Lab Extension
        working-directory: ./podman-desktop-extension-ai-lab
        run: sed -i -E "s/(@sha256:[0-9a-f]+)/:${{ github.event_name != 'workflow_dispatch' && 'latest' || github.event.inputs.tag }}/g" packages/backend/src/assets/inference-images.json

      - name: Build Image
        working-directory: ./podman-desktop-extension-ai-lab
        id: build-image
        run: |
          pnpm build
          podman build -t local_ai_lab_image ./
          CONTAINER_ID=$(podman create localhost/local_ai_lab_image --entrypoint "")
          mkdir -p tests/playwright/tests/playwright/output/ai-lab-tests-pd/plugins
          podman export $CONTAINER_ID | tar -x -C tests/playwright/tests/playwright/output/ai-lab-tests-pd/plugins/
          podman rm -f $CONTAINER_ID
          podman rmi -f localhost/local_ai_lab_image:latest

      - name: Run E2E tests
        working-directory: ./podman-desktop-extension-ai-lab
        env:
          PODMAN_DESKTOP_ARGS: ${{ github.workspace }}/podman-desktop
          EXTENSION_PREINSTALLED: true
        run: pnpm test:e2e

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          annotate_only: true
          fail_on_failure: true
          include_passed: true
          detailed_summary: true
          require_tests:  true
          report_paths: '**/*results.xml'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-check
          path: |
            ./**/tests/**/output/
            !./**/*.gguf
            !./**/*.bin
            !./**/output/videos/*
            !./**/output/traces/*

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-check-videos
          path: ./**/output/videos/*

      - name: Upload test traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-check-traces
          path: ./**/output/traces/*

